### ISSUE TITLE
PSQL version

### ISSUE THREAD

**Issue by Angryrou** [rabbit721/QPPNet#1]
Hi, 

Thanks for sharing your open-source implementation for QPPNet.

 **May I ask the PostgreSQL version you used?** -- I would like to collect new traces and reuse the code. 

Thanks in advance.

**Comment by rabbit721** [comment]
Yeah sure, I used (PostgreSQL) 12.2 for the TPC-H benchmark. Let me know if you have other questions.

**Comment by boxinge** [comment]
I can't get the TPC-H benchmarked with PostgresSQL 1G data to train the model. This data access cannot be found for 404. Can you send me a copy of TPC-H benchmarked with PostgresSQL 1G data.
