### ISSUE TITLE
Cannot obtain TPC-H benchmarked with PostgresSQL 1G

### ISSUE THREAD

**Issue by boxinge** [rabbit721/QPPNet#3]
I can't get the TPC-H benchmarked with PostgresSQL 1G data to train the model. This data access cannot be found for 404. Can you send me a copy of TPC-H benchmarked with PostgresSQL 1G data.

**Comment by JianhuiWei7** [comment]
hello, did you get the dataset for the code? TPC-H benchmarked with PostgresSQL

**Comment by apavlo** [comment]
The student graduated and is no longer working on this project. The newer version is here:

https://github.com/cmu-db/qppnet

You have to collect the training data yourself.
